### PR TITLE
docs(readme.md): fix typo GIVEN - WHEN - THEN

### PR DESCRIPTION
**Pull request by maartentibau**

### CODE REVIEW

**Comment by shairez** [comment]
Nice catch @maartentibau !
Thanks a lot! ❤️

**Comment by shairez** [comment]
@all-contributors please add @maartentibau for Documentation and Infra

**Comment by maartentibau** [comment]
Thank you! 🙏

**Comment by shairez** [comment]
Sure thing!
Thank you! 😄 🙏

**Pull request merged**
