### PR TITLE
Guard against `then` being a getter that throws the second time around

### PR DESCRIPTION
**Pull request by benjamingr**

### CODE REVIEW

**Comment by shairez** [comment]
Thanks @benjamingr !

What's the test we should add in order to cover this branch of code? (to keep the coverage numbers at 100% 😄 )

**Comment by benjamingr** [comment]
> What's the test we should add in order to cover this branch of code? (to keep the coverage numbers at 100% 😄 )

https://github.com/promises-aplus/promises-tests/blob/4786505fcb0cafabc5f5ce087e1df86358de2da6/lib/tests/2.3.3.js#L211-L213

Basically, potentialPromise being something like:

```js
const potentialPromise = {
  called: false,
  get then() {
    if (!called) {
      called = true;
      return Promise.resolve().then.bind(Promise.resolve());
    }
    throw new Error('OMG why would anyone do this oh wait the reason this test exists in A+ is that some libraries actually do this but why?');
  }
}
```

**Comment by shairez** [comment]
Thanks again @benjamingr 
(sorry for the late late late reply here :)

**Comment by shairez** [comment]
@all-contributors please add @benjamingr for their code ideas and maintenance

**Pull request merged**
